config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'charges/new'

  get 'charges/create'

  get 'cart/checkout', to: 'cart#checkout', as: 'checkout'

  get '/category/:id', to: "products#category", as: 'category', number: /\d+/
  get '/all', to: "products#index"

  get '/new', to: 'products#new', as: 'new'

  get '/search', to: "products#search", as: 'search'

  get '/products/:id', to: 'products#products_page', as: 'pp', number: /\d+/

  post '/cart/:id' => 'cart#this_cart', as: 'cart'

  get '/cart/show', to: 'cart#show', as: 'show'

  post '/cart/destroy/:id', to: 'cart#destroy', as: 'destroy'

  resources :charges, only: [:new, :create]

  devise_for :users, skip: :all




  root to: 'products#index'
  get 'products/index'

  # get 'products/shirts' to 'products#shirts'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
has_many :products

  def add_item(product_id,quantity)

    product = Product.where('id = ?', product_id).first
    cart_item = Cart.where('product_id = ?', product_id).first
    full_price = quantity.to_f * product.productPrice

    if cart_item
      cart_item.quantity + 1
    else
      object = Cart.new(:name => product.name, :quantity => quantity, :price => product.productPrice, :product_id => product.id, :full_price => full_price)
      object.save
    end
    save
  end



end

app/controllers/cart_controller.rb
class CartController < ApplicationController

  before_action :init_sess

  def this_cart
    @categories_all = Category.all
    @products_all = Product.all

    id = params[:id].to_i
    q = params[:quantity].to_i

    if session[:zz].any? {|h| h['id'] == id}
      session[:zz].each do |val|
          if val['id']==id
            val['q'] = q
          end
       end
    else
      session[:zz] << {:id => id, :q => q}
    end
    redirect_to :action => :show
  end

  def init_sess
    session[:zz] ||= []
  end

  def show
    @categories_all = Category.all
    @products_all = Product.all

    @mycart = session[:zz]

  end

  def checkout
    @categories_all = Category.all
      @products_all = Product.all
    @mycart = session[:zz]
    @pass_sub = params[:sub]

    if(user_signed_in?)
      @curr_user = User.where('name LIKE ?', current_user.name)

     @curr_user.each do |user|
       @ppp = user.province_id
     end

     @curr_pro = Province.where('id LIKE ?', @ppp)

     @curr_pro.each do |province|
       @ggst = province.gst
       @ppst = province.pst
     end

     @you_ggst = @pass_sub.to_f * @ggst.to_f
     @you_ggst.to_f

     @you_ppst = @pass_sub.to_f * @ppst.to_f
     @you_ppst.to_f

     @grandtot = @you_ggst + @you_ppst + @pass_sub.to_f
     @grandtot.to_f



    else
      redirect_to user_session_path
    end
  end

  def destroy
    @categories_all = Category.all
    @products_all = Product.all

    id_destroy = params[:id].to_i

    if session[:zz].any? {|h| h['id'] == id_destroy}
      session[:zz].each do |val|
          if val['id']==id_destroy
            session[:zz].delete(val)
          end
    end

    redirect_to :action => :show

  end

end

end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/checkout.html.erb
<%= render partial: 'shared/headerpart' %>

</br>
</br>
<h2>Your Cart </h2>
<table>

  <% if @mycart.empty? %>
  <p>Your cart is empty </p>

  <% else %>
  <% total = 0%>
  <% prodTotal = 0 %>
  <% @mycart.each do |val| %>


    <% @products_all.each do |product| %>
      <% if product.id == val['id']%>
       <tr>

         <td><b>Product:</b> <%=product.name %> </td>
         <tr><td> <b>Quantity:</b> <%= val['q'] %> </td></tr>
         <% prodTotal = val['q'].to_d * product.sale_price %>

         <% total += prodTotal %>


       </tr>

      <% end %>

    <% end %>

  <% end %>
  
  <tr><td> <b>Sub Total:</b> <%= total %> </td></tr>
  <tr><td> <b>PST:</b> <%= @you_ppst %> </td></tr>
  <tr><td> <b>GST:</b> <%= @you_ggst %> </td></tr>
  <tr><td> <b>Total:</b> <%= @grandtot %> </td></tr>
  <td>  <%= submit_tag "Proceed to Pay" %></td>

  <% end %>


</table>
<%= render partial: 'shared/footer' %>

app/views/cart/destroy.html.erb
destroy page!!

<%= @ii %>

app/views/cart/show.html.erb
<%= render partial: 'shared/headerpart' %>
</br>
</br>
<h2>Your Cart </h2>
<table>

  <% if @mycart.empty? %>
  <p>Your cart is empty </p>

  <% else %>
  <% total = 0%>
  <% prodTotal = 0 %>
  <% @mycart.each do |val| %>


    <% @products_all.each do |product| %>
      <% if product.id == val['id']%>
       <tr>
         <td> <%= product.name %> </td>
         <td>  <%= val['q'] %> </td>
         <% prodTotal = val['q'].to_d * product.sale_price %>
         <td> <%= prodTotal %></td>
         <% total += prodTotal %>
         <td> <%= button_to 'Remove from cart', {:controller => "cart", :action => "destroy", :id => val['id']} , :method=>:post  %></td>
       </tr>

      <% end %>

    <% end %>
  <% end %>
  <tr>Total : $<%=total %> CAD</tr>


  <%= form_tag checkout_path, method: 'get' do %>

  <input id="sub" name= "sub" value= '<%=total%>'/>
  <!-- <%=  button_to 'Proceed to checkout', {:controller => "cart", :action => "checkout"}, :method => :get %> -->
  <%= submit_tag "Proceed to checkout" %>

  <% end %>

  <% end %>


</table>

<%= render partial: 'shared/footer' %>