config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'charges/new'

  get 'charges/create'

  get 'cart/checkout', to: 'cart#checkout', as: 'checkout'

  get '/category/:id', to: "products#category", as: 'category', number: /\d+/
  get '/all', to: "products#index"

  get '/new', to: 'products#new', as: 'new'

  get '/search', to: "products#search", as: 'search'

  get '/products/:id', to: 'products#products_page', as: 'pp', number: /\d+/

  post '/cart/:id' => 'cart#this_cart', as: 'cart'

  get '/cart/show', to: 'cart#show', as: 'show'

  post '/cart/destroy/:id', to: 'cart#destroy', as: 'destroy'

  resources :charges, only: [:new, :create]

  devise_for :users, skip: :all




  root to: 'products#index'
  get 'products/index'

  # get 'products/shirts' to 'products#shirts'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_catmenus.html.erb
<ul>
  <li><%= link_to 'new', new_path %> </li>
<li>  <%= link_to 'all', all_path %> </li>
  <% @categories_all.each do |category| %>
    <li><%= link_to category.name, category_path(category.id) %>  </li>
    <% end %>

</ul>

app/views/shared/_common.html.erb
<table>
 <% @products_all.each do |product| %>
 <tr><h4><b><%= product.name%></b></h4></tr>
 <tr><p><%= image_tag product.productImage %></p></tr>
 <tr><h4><b><%= product.productPrice%></b></h4></tr>
 <!-- <tr><p><%= product.productDescription %></p></tr> -->
 <% end %>

</table>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="py-5 bg-dark">
  <div class="container">
    <p class="m-0 text-center text-white">Copyright &copy; RJK 2017</p>
  </div>
  <!-- /.container -->
</footer>

app/views/shared/_header.html.erb
<%= form_tag search_path, method: 'get' do %>
  <%= select_tag "categories", options_from_collection_for_select(@categories_all, "id", "name"), include_blank: "All Categories" %>
  <%= text_field_tag :search_keywords %>
  <%= submit_tag "Search" %>
<% end %>

app/views/shared/_headerpart.html.erb
<!-- Navigation -->
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link"
            <%= link_to 'Home', root_path %>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="contact.html">Contact</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownPortfolio">

            <% @categories_all.each do |category| %>

              <a class="dropdown-item">
                <%= link_to category.name, category_path(category.id) %>
              </a>
            <% end %>

          </div>
        </li>

      </ul>
    </div>
    <a >
      <div>
        <%= form_tag search_path, method: 'get' do %>
          <%= select_tag "categories", options_from_collection_for_select(@categories_all, "id", "name"), include_blank: "All Categories" %>
          <%= text_field_tag :search_keywords %>
          <%= submit_tag "Search" %>
        <% end %>
      </div>


    </a>

    <div>

        <%= image_submit_tag("cart1.png") %>


    </div>
    <% if(user_signed_in?) %>
    <li class="nav-item">
     <li style="color:#ffffff">Hi  <%= current_user.name %></li>
    <a class = "nav-link" <%= link_to "Log Out", destroy_user_session_path, method: 'delete' %> </a>
    </li>
    <% else %>
    <li class="nav-item">
    <a  style="color:#ffffff" <%= link_to "Log in", user_session_path %> </a>
    </li>
    <li class="nav-item">
    <a  style="color:#ffffff" <%= link_to "Sign Up", new_user_registration_path %> </a>
    </li>
    <% end %>


  </div>
</nav>

app/views/shared/_simplifiedhead.html.erb
<!-- Navigation -->
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link"
            <%= link_to 'Home', root_path %>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="contact.html">Contact</a>
        </li>
    

      </ul>
    </div>
    <a >

    </a>

    <div>

        <%= image_submit_tag("cart1.png") %>


    </div>


  </div>
</nav>