config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'charges/new'

  get 'charges/create'

  get 'cart/checkout', to: 'cart#checkout', as: 'checkout'

  get '/category/:id', to: "products#category", as: 'category', number: /\d+/
  get '/all', to: "products#index"

  get '/new', to: 'products#new', as: 'new'

  get '/search', to: "products#search", as: 'search'

  get '/products/:id', to: 'products#products_page', as: 'pp', number: /\d+/

  post '/cart/:id' => 'cart#this_cart', as: 'cart'

  get '/cart/show', to: 'cart#show', as: 'show'

  post '/cart/destroy/:id', to: 'cart#destroy', as: 'destroy'

  resources :charges, only: [:new, :create]

  devise_for :users, skip: :all




  root to: 'products#index'
  get 'products/index'

  # get 'products/shirts' to 'products#shirts'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  mount_uploader :productImage, ImagerUploader
  belongs_to :category


  validates :name, presence: true

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products_all = Product.all
    @categories_all = Category.all
  end
  def category
    @products_all = Product.all
    @categories_all = Category.all
    @item = params[:id]
  end

  def search
    @products_all = Product.all
    @categories_all = Category.all

    keywords = "%" + params[:search_keywords] + "%";
    cat = "%" + params[:categories] + "%";

    if params[:categories] == ''
      @found_products = Product.where("name LIKE '#{keywords}' or productDescription LIKE '#{keywords}'")
    else
      @found_products = Product.where("category_id LIKE '#{cat}' and name LIKE '#{keywords}'")
    end

  end

  def new
    @products_all = Product.all
    @categories_all = Category.all
    today = DateTime.now
    sale_item_date = (today - 2).to_date
    @new_prods = Product.where("created_at > '#{sale_item_date}'")
  end

  def products_page
    @categories_all = Category.all
    id = params[:id]
    @products_all = Product.all.where("id LIKE ?", id)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/category.html.erb
<%= render partial: 'shared/headerpart' %>

</br></br>

<h3>Products</h3>
<div class="container">
  <div class="row">

        <% @products_all.each do |product| %>

          <% if product.category_id == @item.to_i %>
          <div class="col-lg-4 mb-4">
              <div class="card h-100">
              <h4 class="card-header"><b><%= link_to product.name, pp_path(product.id)%></b></h4>
              <div class="card-body">
                <%= link_to (image_tag product.productImage), pp_path(product.id) %>
              </div>
              <div class="card-footer">
                <%= link_to product.productDescription, pp_path(product.id) %></div>
            </div>
         </div>
          <% end %>

        <% end %>

  </div>
</div>
<%= render partial: 'shared/footer' %>

app/views/products/index.html.erb

<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>White Curry Trends</title>

    <!-- Bootstrap core CSS -->
    <link href="app/assets/stylesheets/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="app/assets/stylesheets/modern-business.css" rel="stylesheet">

  </head>
  <%= render partial: 'shared/headerpart' %>
  <body>



    <header>
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner" role="listbox">
          <!-- Slide One - Set the background image for this slide in the line below -->
          <div class="carousel-item active" style="background-image: url('https://wallpaper.wiki/wp-content/uploads/2017/06/Earthbound-Minimalist-Desktop-Wallpaper.png')">
            <div class="carousel-caption d-none d-md-block">
              <!-- <h3>First Slide</h3>
              <p>This is a description for the first slide.</p> -->
            </div>
          </div>
          <!-- Slide Two - Set the background image for this slide in the line below -->
          <div class="carousel-item">
            <%= image_tag("wc.jpg", :alt => "wc") %>
            <div class="carousel-caption d-none d-md-block">
            </div>
          </div>

        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </header>

    <!-- Page Content -->
    <div class="container">
      

      <h1 class="my-4">White Curry Trends</h1>

      <!-- Marketing Icons Section -->
      <div class="row">

        <% @products_all.each do |product| %>

        <div class="col-lg-4 mb-4">
          <div class="card h-100">
            <h4 class="card-header"><%= link_to product.name, pp_path(product.id)%></h4>
            <div class="card-body">
              <%= link_to (image_tag product.productImage), pp_path(product.id) %>
            </div>
            <div class="card-footer">
              <% if(product.sale_price < product.productPrice)%>
              <strike>$<%= product.productPrice %></strike>
              $<%= product.sale_price %> CAD
              <% else %>
              $<%= product.sale_price %> CAD
              <% end %>
            </div>
          </div>
        </div>

        <% end %>




      </div>
      <!-- /.row -->

</div>

    <%= render partial: 'shared/footer' %>

    <!-- Bootstrap core JavaScript -->
    <script src="app/assets/javascripts/jquery.min.js"></script>
    <script src="app/assets/javascripts/bootstrap.bundle.min.js"></script>

  </body>

</html>

app/views/products/new.html.erb
<h2>New Products</h2>

<table>
 <% @new_prods.each do |product| %>
 <tr><h4><b><%= product.name%></b></h4></tr>
 <tr><p><%= image_tag product.productImage %></p></tr>
 <tr><p><%= product.productDescription %></p></tr>
 <% end %>
</table>

app/views/products/products_page.html.erb
  <%= render partial: 'shared/headerpart' %>
</br></br>

<div class="container">
  <div class="row">
    <% @products_all.each do |product| %>
    <div class="col-lg-4 mb-4">
        <div class="card h-100">
        <h4 class="card-header"><b><%= product.name%></b></h4>
        <div class="card-body"><%= image_tag product.productImage %></div>
        <div class="card-footer"> $<%= product.productPrice%> CAD</div>

        <% @quantity_array = [] %>
        <% i = 0 %>

        <% product.productStockQuantity.times { @quantity_array << i+=1} %>

        <%= form_tag cart_path(id: product.id), method: 'post' do %>

           <%= select_tag "quantity", options_for_select(@quantity_array) %>
           <%= submit_tag "Add to cart" %>
         </div>
      </div>
        <% end %>

    <% end %>
  </div>
</div>
<%= render partial: 'shared/footer' %>

app/views/products/search.html.erb
<%= render partial: 'shared/headerpart' %>
</br></br>
<h2>Search Results</h2>
<div class="container">
  <div class="row">


  <% if @found_products.empty? %>
  <p>No results found </p>
  <% end%>
  <% else %>
  <% @found_products.each do |product| %>
  <div class="col-lg-4 mb-4">
      <div class="card h-100">
  <h4 class="card-header"><b><%= product.name%></b></h4>
  <div class="card-body"><%= image_tag product.productImage %></div>
  <div class="card-footer"><%= product.productDescription %></div>
</div>
</div>
  <% end %>
</div>
</div>
  <%= render partial: 'shared/footer' %>